version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    links:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    links:
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: contractor-approval
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
