version: "3.9"

x-app-base: &app-base
  build: .
  volumes:
    - .:/app
  environment:
    DJANGO_SETTINGS_MODULE: config.settings.local

services:
  web:
    <<: *app-base
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    depends_on:
      - celery
      - celery-beat
      - redis
      - postgres
    stdin_open: true
    tty: true
  celery:
    <<: *app-base
    command: celery -A config worker -l INFO
    links:
      - redis
  celery-beat:
    <<: *app-base
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    links:
      - postgres
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: resourcing-approval
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
